"""reminder time

Revision ID: 8f63775327de
Revises: 9c7d109d4877
Create Date: 2021-09-07 10:10:56.831809

"""
import datetime

from src.data.data import TIME_ZONE

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f63775327de'
down_revision = '9c7d109d4877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reminder_time', sa.Time(timezone=True)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reminder_time')
    # ### end Alembic commands ###
